### ISSUE TITLE
【Bug反馈】0.1.0版本内置的exe服务端无法正常启动

### ISSUE THREAD

**Issue by ITManCHINA** [lgc2333/BetterNCM-6K-Labs#1]
## 可能有用的信息
网易云版本：2.10.13
betterncm版本：1.3.4
6K Labs版本：0.1.0
系统版本：Win 11 23H2 22631.4460 amd64

## 遇到的问题
一开始插件一直提示报错，6K那边配置好了样式，并且OBS内置浏览器也配置好了（如图）
![image](https://github.com/user-attachments/assets/b841dbe2-5453-4659-ad4a-d8b7bcbe7963)
但后面发现插件端一直在报错
![image](https://github.com/user-attachments/assets/31fd1daa-a83b-4a1a-9fb5-e58e27476351)
最后解压插件后才发现是服务端（bncm-6k-labs-server.exe）无法启动
![image](https://github.com/user-attachments/assets/e9c07c96-ca8e-4470-909d-c2c90da7df64)

## 求助
需要等待新的服务端吗？

**Comment by lgc2333** [comment]
可能是我用 github actions 编译出来的东西有问题，我明天有时间研究一下

**Comment by lgc2333** [comment]
已修复，可以先下载这里的服务端替换使用
https://github.com/lgc2333/BetterNCM-6K-Labs/blob/dist/bncm-6k-labs-server.exe

**Comment by ITManCHINA** [comment]
> 已修复，可以先下载这里的服务端替换使用 https://github.com/lgc2333/BetterNCM-6K-Labs/blob/dist/bncm-6k-labs-server.exe

Cool，我试试
