### ISSUE TITLE
后台驻留导致网易云重启后betterncm崩溃

### ISSUE THREAD

**Issue by gongfuture** [lgc2333/BetterNCM-6K-Labs#2]
```
---------------------------
BetterNCM
---------------------------
BetterNCM 崩溃了！

BetterNCM 将不会运行
网易云将有可能崩溃

崩溃原因：remove_all: 拒绝访问。: "C:/betterncm/plugins_runtime\6k-labs"

这有可能是因为你运行了多个实例的网易云，请只点击一次，然后等待网易云打开。不要多次点击。

This is probably because you ran multiple instances of CloudMusic. Please only click once.
---------------------------
确定   
---------------------------
```

**Comment by lgc2333** [comment]
可以尝试一下吗

```cmd
taskkill /im bncm-6k-labs-server.exe /f
```

**Comment by lgc2333** [comment]
后续我把这些东西扔进appdata temp里吧，这个后台驻留不好解决

**Comment by gongfuture** [comment]
> 可以尝试一下吗
> 
> ```batchfile
> taskkill /im bncm-6k-labs-server.exe /f
> ```

啊，我知道要杀进程，但是这个问题总得解决，总不能每次重启网易云之前都要杀一下吧（）

> 后续我把这些东西扔进appdata temp里吧，这个后台驻留不好解决

或许可以在启动时加一个检测？已经打开的情况下直接使用或者杀掉重开？我没看过代码纯瞎想的（）

注意到 https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller 好像也存在调用外部程序，可能可以参考？

**Comment by lgc2333** [comment]
目前我写的是会复用已在后台的进程（通过保存pid，但是这个方法还是不太好）
大概了解是什么情况了，应该是betterncm会解压插件运行，而后端服务器在运行时会占用文件导致bncm无法删除或替换它，因为我是开发环境所以不存在这些问题

**Comment by Lukoning** [comment]
同样的问题，昨天重启网易云时遇到了

可以参考RevivedUnblockInstaller，后端服务与前端插件分离，甚至于可以直接在插件设置页切换后端版本
不过这样的话后端服务需要单独下载

另外，似乎InfLink和RevivedUnblockInstaller都没有直接在插件目录中运行服务的情况

**Comment by lgc2333** [comment]
https://github.com/lgc2333/BetterNCM-6K-Labs/releases/tag/v0.2.0

如果有问题请继续在此处跟进
